sports_ecom/neona_sports/urls.py
from django.contrib import admin
from django.urls import path
from .import views


urlpatterns = [
    
    path('', views.hi, name="home"),
    path('loginpage/', views.loginpage, name="loginpage"),
    path('logoutpage/', views.logoutpage, name="logoutpage"),
    path('product/', views.product, name="product"),
    path('product/<str:id>', views.product_detail, name="product_detail"),
    path('base/', views.base, name="base"),
    path('contact/', views.Contact, name="contact"),
    path('profile/', views.profile, name="profile"), 
    path('aboutus/', views.Aboutus, name='aboutus'),
 
]

sports_ecom/sports_ecom/urls.py
from django.contrib import admin
from django.urls import path, include
from neona_sports import views

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('neona_sports.urls')),
    path('signup/', views.signup, name="signup"),

    # Add to cart functinality
    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/', views.item_increment, name='item_increment'),
    path('cart/item_decrement/<int:id>/', views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    path('cart/cart-detail/',views.cart_detail,name='cart_detail'),

    path("accounts/", include("django.contrib.auth.urls")),

    # Reset password
    path('password_reset/',auth_views.PasswordResetView.as_view(),name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),

    # admin contacts
    path('adminpanel/', views.admin, name="adminpanel"),
    path('add/',views.ADD, name='add'),
    path('edit', views.Edit, name='edit'),
    path('update/<str:id>', views.Update, name='update'),
    path('delete/<str:id>', views.Delete, name="delete"),

    
    path('changepass/', views.Changepass, name="changepass"),
    
    #admin login
    path('adminlogin/', views.adminlogin, name="adminlogin"),
    path('dashboard/', views.dashboard, name="dashboard"),

    # admin Products
    path('prodadmin/', views.prodadmin, name="prodadmin"),
    path('add-product/', views.addProduct, name="add-product"),
    path('edit-product/<str:st>', views.editProduct, name="edit-product"),
    path('delete-product/<str:st>', views.deleteProduct, name="delete-product"),

    #wishlist
    path('wishlist/',views.Wishlist, name='wishlist'),

    #khalti
    path('khalti', views.khalti, name='khalti'),
    path('khalti-verify/', views.khalti_verify, name='khaltiverify'),

    #Checkout
    path('checkout', views.Checkout, name='checkout'),
   
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sports_ecom/neona_sports/models.py
from django.db import models
from django.utils.html import mark_safe
from django.contrib.auth.models import User
from datetime import datetime, date



# Create your models here.


class Contact_us(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)
    subject = models.CharField(max_length=300)
    message = models.TextField()
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.email
    

    
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE) # Delete profile when user is deleted
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'    
  

class Main_category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Category(models.Model):
    main_category = models.ForeignKey(Main_category, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    


class Product(models.Model):
    Availibilty = (('In Stock','In Stock'), ("Out of Stock","Out of Stock"))
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default='1')
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=200, default='')
    price = models.IntegerField(default=0)
    sale = models.CharField(max_length=255)
    image = models.ImageField(upload_to='products/')
    Availibilty = models.CharField(choices=Availibilty,null=True, max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    featured = models.BooleanField(default=False)
   

    def __str__(self):
        return self.name

class Customer(models.Model):
    name=models.CharField(max_length=50, null=True)
    phone=models.CharField(max_length=50, null=True)
    email=models.EmailField()
    date_created=models.DateTimeField(auto_now_add=True, null=True)

    
    def __str__(self):
        return self.name


class Order(models.Model):
    STATUS={
        ('pending', 'pending'),
        ('Out for delivery', 'Out for delivery'),
        ('Delivered','Delivered'),

    }
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    firstname = models.CharField(max_length=100,null=True)
    lastname = models.CharField(max_length=100, null=True)
    email = models.CharField(max_length=50,null=True)
    address = models.CharField(max_length=500,null=True)
    mobile = models.CharField(max_length=20,null=True)
    amount = models.CharField(max_length=100, null=True)
    payment_completed = models.BooleanField(default=False, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)


      
    # def __str__(self):
    #     return self.user


class order_items(models.Model):
    order=models.ForeignKey(Order, on_delete=models.CASCADE)
    product=models.CharField(max_length=200)
    image=models.ImageField(upload_to='products/')
    quantity=models.CharField(max_length=20)
    price=models.CharField(max_length=50)
    total=models.CharField(max_length=1000)

    # def __str__(self):
    #     return self.user

sports_ecom/neona_sports/views.py
import os

from cart.cart import Cart
from django.contrib import messages
from django.contrib.auth import (authenticate, login, logout,
                                 update_session_auth_hash)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.template import RequestContext
import requests


from .models import (Category, Contact_us, Customer, Main_category, Order,
                     Product)

# Create your views here.

def base(request):
    return render(request, 'base.html')


def hi(request):
    data = Product.objects.filter(featured=True).order_by('-id')

    return render(request,'home.html', {'data':data})


def loginpage(request):
    if request.method=="POST":
        user_name=request.POST.get('username')
        pass1=request.POST.get('pass')
        
        
        user=authenticate(request, username=user_name, password=pass1)
        if user is not None:
            login(request,user)
            messages.success(request, "you have logged in successfully")
       
            return redirect('home')
            
        else:
            messages.error(request, "Your Username or Password is incorrect")
          
           

    return render(request,'login.html')
 

def signup(request):
    if request.method=="POST":
        username=request.POST.get('username')
        email=request.POST.get('email')
        pass1=request.POST.get('password1')
        pass2=request.POST.get('password2')
        
        if User.objects.filter(username=username):
            messages.error(request, "username already exist!!")
            return redirect('signup')
        
        if User.objects.filter(email=email):
            messages.error(request, "email already exist!")
            return redirect('signup')        
        
        if pass1!=pass2:
            messages.error(request, "Your Password didn't match") 
            return redirect('signup')
        else:
           my_user=User.objects.create_user(username,email,pass1)
           my_user.save()
           messages.success(request, "Your account has been created")
           return redirect('loginpage')

        
        

    return render(request,'signup.html')    

 
def logoutpage(request):
    logout(request)
    return redirect('loginpage')



def  product(request):
    main_category = Main_category.objects.all().order_by('-id')
    product = Product.objects.filter()
    category = Category.objects.all().order_by('-id')

    categoriesID = request.GET.get('categories')

    if categoriesID:
        product = Product.objects.filter(category = categoriesID)
    else:
        product = Product.objects.all()
   
    data = {
        'main_category' : main_category,
        'product': product,
        'category': category,
    }

    return render(request, 'product.html', data)

def product_detail(request,id):
    product = Product.objects.filter(id = id).first()
    context = {
        'product':product
    }
    return render(request, 'product_detail.html', context)    
    


@login_required(login_url="/loginpage/")
def Contact(request):

    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        subject = request.POST.get('subject')
        message = request.POST.get('message')
        
        messages.success(request, "your contact has been send")

        contact = Contact_us(
            name=name,
            email=email,
            subject=subject,
            message=message,

        )

        contact.save()
        return redirect('home')


    return render(request, "contact.html")



def profile(request):
    # check if the user is authenticated or not
    if request.user.is_authenticated:
        return render(request, 'profile.html')
    else:
        return redirect("loginpage")

def Aboutus(request):
    return render(request, 'aboutus.html')


@login_required(login_url="/users/loginpage/")
def cart_add(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.add(product=product)
    return redirect("cart_detail")


@login_required(login_url="/users/loginpage")
def item_clear(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.remove(product)
    return redirect("cart_detail")


@login_required(login_url="/users/login")
def item_increment(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.add(product=product)
    return redirect("cart_detail")


@login_required(login_url="/users/login")
def item_decrement(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.decrement(product=product)
    return redirect("cart_detail")


@login_required(login_url="/users/login")
def cart_clear(request):
    cart = Cart(request)
    cart.clear()
    return redirect("cart_detail")


@login_required(login_url="/users/login")
def cart_detail(request):
    return render(request, 'cart/cart_detail.html')

def Checkout(request):
    if request.method == 'POST':
        firstname = request.POST.get('firstname')
        lastname = request.POST.get('lastname')
        email = request.POST.get('email')
        address = request.POST.get('address')
        mobile = request.POST.get('mobile')
        
        
        messages.success(request, "your order has been placed")

        order = Order(
            firstname=firstname,
            lastname=lastname,
            email=email,
            address=address,
            mobile=mobile,

        )

        order.save()
        return redirect('khalti')
    
    return render(request, 'checkout.html')

def admin(request):
    contact = Contact_us.objects.filter()

    data = {
        
        'contact': contact,
    
    }
    return render(request, 'admin/adminpanel.html', data)

def ADD(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        subject = request.POST.get('subject')
        message = request.POST.get('message')

        contact = Contact_us(
            name=name,
            email=email,
            subject=subject,
            message=message,

        )
        contact.save()

        return redirect('admin')
    
    return render(request, 'admin/adminpanel.html')


def Edit(request):
    contact = Contact_us.objects.filter()
    

    context = {
        'contact':contact,
    }
    return redirect(request, 'admin/adminpanel.html', context)


def Update(request,id):
    if request.method == "POST":
        name = request.POST.get('name')
        email = request.POST.get('email')
        subject = request.POST.get('subject')
        message = request.POST.get('message')
    

        contact = Contact_us(
            id = id,
            name = name,
            email = email,
            subject = subject,
            message = message,

        )
        contact.save()

        return redirect('admin')
         
 
    return redirect(request, 'admin/adminpanel.html')

def Delete(request, id):
    contact = Contact_us.objects.filter(id=id)
    contact.delete()

    context = {
        'contact':contact
    }

    return redirect('admin', context)

def Changepass(request):
    if request.method == "POST":
      passchange = PasswordChangeForm(user=request.user, data=request.POST)
      if passchange.is_valid():
        passchange.save()
        update_session_auth_hash(request, passchange.user)
        return HttpResponseRedirect('/profile/')
    else:
        passchange = PasswordChangeForm(user=request.user)
    return render(request, 'changepassword.html', {'form':passchange})


def prodadmin(request):
    product = Product.objects.filter()

    data = {
        
        'product': product,
    
    }
    return render(request, 'admin/productadmin.html', data)


def dashboard(request):
    order=Order.objects.all()
    customer=Customer.objects.all()
    total_customer=customer.count()
    total_order=order.count()
    

    context={
        'order':order,
        'customer':customer,
        'total_customer':total_customer,
        'total_order':total_order,
        
    }

    return render(request, 'admin/adimindashboard.html', context)

def adminlogin(request):
   
     if request.method=="POST":
        user_name=request.POST.get('username')
        pass1=request.POST.get('pass')
        
        
        user=authenticate(request, username=user_name, password=pass1)
        if user is not None and user.is_staff:
            login(request,user)
            messages.success(request, "you have logged in successfully")
            return redirect('dashboard')
            
        else:
            messages.error(request, "Your Username or Password is incorrect")
          
     return render(request, 'admin/adminlogin.html')




def addProduct(request):
    if request.method == "POST":
        prod = Product()
        prod.name = request.POST.get('name')
        prod.price = request.POST.get('price')
        prod.categories = request.POST.get('categories')

        if len(request.FILES) != 0:
            prod.image = request.FILES['image']

        prod.save()
        messages.success(request,"Product succesfully added")
        return redirect('prodadmin')    

    return render(request, 'admin/addproduct.html')


def editProduct(request, st):
    prod = Product.objects.get(id=st)

    if request.method == "POST":
        if len(request.FILES) !=0:
            if len(prod.image) > 0:
                os.remove(prod.image.path)
            prod.image = request.FILES['image']
        prod.name = request.POST.get('name')
        prod.price = request.POST.get('price')
        prod.categories = request.POST.get('categories')

sports_ecom/neona_sports/templates/aboutus.html
{% extends 'base.html' %}
{% block content %}
<style>
    .container{
        padding:40px
    }

   .iframe{
    position: center;
   }
   p{
    text-indent: 50px;
    
   }
</style>
<div class="container">
<h1 style="text-align:center;">About Us</h1><br><br><br>
<div class="small-container">
<p style="text-align:left;">“Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore fugiat quod corporis delectus
    sequi laudantium molestias vero distinctio, qui numquam dolore, corrupti, enim consectetur cum? 

    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque a quam nulla ipsa natus quisquam!
    
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum ex odit tenetur alias expedita impedit in veritatis mollitia ipsam quae et quia, deleniti facere praesentium sunt assumenda earum saepe aperiam ullam sit. Tempora animi maxime a velit soluta laboriosam quo!
    
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem, tempora!”
</p>
</div>
<h3 >Google Map</h3>
<iframe 
    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d9225.939085309163!2d85.31064871008748!3d27.73287238493181!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39eb19b41d687413%3A0x4649cb495c19165b!2sNeona&#39;s%20Sports%20Zone!5e0!3m2!1sen!2snp!4v1682065477794!5m2!1sen!2snp"
    width="500" height="400" style="border:0;" allowfullscreen="" loading="lazy"
    referrerpolicy="no-referrer-when-downgrade"></iframe>
</div>

{% endblock %}

sports_ecom/neona_sports/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
        integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    {% load static %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=League+Spartan:wght@200;300;400;500;600;700;800&display=swap"
        rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/main.css'%}">
    <style src="{% static 'grid.js' %}"></style>

    <title>Homepage</title>

</head>

<body>
    <!-- header -->
    <header id="header">
        <img src="{% static 'images/logo1.png'%}">

        <div>
            <ul id="navbar">
               

                <li><a href="{% url 'home' %}">Home</a></li>
                
                <div class="dropdown">
                    <li><a href="{% url 'product' %}" class="dropbtn">Product</a>
                        <i class="fa fa-caret-down"></i>
                    </li>
                    <div class="dropdown-content">
                        
                        <div class="row">

                            {% for i in main_category %}
                            <div class="column">
                                <h3>{{i.name}}</h3>
                                {% for cat in i.category_set.all %}
                                <a href="/product/?categories={{cat.id}}">{{cat.name}}</a>
                                {% endfor %}
                            </div>
                            {% endfor %}

                        </div>
                        

                    </div>
                </div>

                
                <li><a href="{% url 'contact' %}">Contact</a></li>
                <li><a href="{% url 'loginpage' %}">Account</a></li>
                <li><a href="{% url 'aboutus' %}">About</a></li>

                <div class="dropbutton">
                    <li><a class="dropbtns"><i class='fas fa-user-alt'></i>{{user.username}}</a></li>
                    <div class="dropdown-contents">
                      <a href="{% url 'profile' %}"><i class='fas fa-user-alt'></i>Profile</a>
                      <a href="{% url 'logoutpage' %}">Logout</a>
                   
                    </div>
                  </div>

               
            </ul>
        </div>

    </header>

    {% block content %}


    {% endblock %}



    <!-- START: footer -->
    <footer class="section-p1">
        <!-- contact -->
        <div class="col">
            <img class="logo" src="img/logo122.png" alt="">
            <h4>Contact</h4>
            <p><strong>Address: </strong>samakhusi, Kathmandu</p>
            <p><strong>Phone: </strong>98766353</p>
            <p><strong>Hours: </strong> 8:00am - 7.00pm, Mon - Sat</p>
            <!-- social icons -->
            <div class="follow">
                <h4>Follow us</h4>
                <div class="icon">
                    <i class="fab fa-twitter"></i>
                    <i class="fab fa-facebook-f"></i>
                    <i class="fab fa-instagram"></i>
                    <i class="fab fa-youtube"></i>
                    <i class="fab fa-pinterest-p"></i>
                </div>
            </div>
        </div>
        <!-- about info -->
        <div class="col">
            <h4>About</h4>
            <a href="{% url 'aboutus' %}">About Us</a>
            <a href="{% url 'contact' %}">Contact Us</a>
        </div>
        <!-- account info -->
        <div class="col">
            <h4>My Account</h4>
            <a href="{% url 'signup' %}">Sign In</a>
            <a href="/cart/cart-detail">View Cart</a>
            <a href="#">My Wishlist</a>
            <a href="#">Help</a>
        </div>
        <!-- install -->
        <div class="col install">
            <h4>Install App</h4>
            <p>From App Store or Google Play Store</p>
         
            <p>Secured Payment Gateways</p>
          
        </div>

        <div class="copyright">
            <p>Neona Sport, Samakhusi, Kathmandu
        </div>
    </footer>
    <!-- END -->

</body>

</html>

sports_ecom/neona_sports/templates/cart.html
<!DOCTYPE html>
<html>
<head>
    <title>cart</title>
    
</head>
{% load static %}
<link rel="stylesheet" href="{% static 'css/cart.css'%}"> 

   
<body>
    


    <div class="header">
        <div class="container">
            <div class="navbar">
                <img src="{% static 'images/logo1.png'%}" width="80px">    
                    
               
                <nav>
        <ul>
            <li><a href="home">Home</a></li>
            <li><a href="">Products</a></li>
            <li><a href="">About</a></li>
            <li><a href=""></a>Contact</a></li>
            <li><a href="{% url 'logoutpage' %}">Logout</a></li>
            
        
        </ul>
                </nav>
             </div>
             
             </div>
        
        </div>
        




<!-- cart items details -->
<div class="small-container cart-page">

    <table>
        <tr>
            <th>Product</th>
            <th>Quantity</th>
            <th>Subtotal</th>
        </tr>
        <tr>
            <td>
                <div class="cart-info">
                    <img src="{% static 'images/shoe2.jpg'%}">
                    <div>
                        <p>Shoes</p>
                        <small>Price: Rs.1340</small>
                        <br>
                        <a href="">Remove</a>
                    </div>
                </div>
            </td>
            <td><input type="number" value="1"></td>
            <td>Rs.1340</td>
        </tr>
    
        <tr>
            <td>
                <div class="cart-info">
                    <img src="images/buy-3.jpg">
                    <div>
                        <p>shoes</p>
                        <small>Price: Rs.1230</small>
                        <br>
                        <a href="">Remove</a>
                    </div>
                </div>
            </td>
            <td><input type="number" value="1"></td>
            <td>Rs.1230</td>
        </tr>
    </table>

    <div class="total-price">

        <table>
            <tr>
                <td>Subtotal</td>
                <td>Rs.2570</td>
            </tr>
            <tr>
                <td>Delivery charge</td>
                <td>Rs.100</td>
            </tr>
            <tr>
                <td>Total</td>
                <td>Rs.2670</td>
            </tr>
        </table>

    </div>

</div>


<!-- footer -->
   
<div class="footer">
    <div class="container">
        <div class="row">
            <div class="footer-col-1">
                <h3>Shop Here</h3>
                <ul>
                    <li>Shoes</li>
                    <li>T-Shirts</li>
                    <li>and many more</li>
                    
                </ul>
            </div>
            <div class="footer-col-2">
                <h3> Our Motto</h3>
              
                <p>Our purpose is to assist you to meet your need for day-to-day in sports.</p>
            </div>
            <div class="footer-col-3">
                <h3>Useful Links</h3>
                <ul>
                    <li>Faqs</li>
                    <li>Blog Post</li>
                    <li>About Us</li>
                    <li>Contact Us</li>
                </ul>
            </div>
            <div class="footer-col-4">
                <h3>Follow Us</h3>
                <ul>
                    <li>Facebook</li>
                    <li>Twitter</li>
                    <li>Instagram</li>
                    <li>YouTube</li>
                </ul>
            </div>
        </div>
        <hr>
        <p class="copyright">Copyright 2023</p>
    </div>
</div>   



   
</body>
</html>

sports_ecom/neona_sports/templates/changepassword.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/chpass.css'%}"> 



<div class="loginbox">    
    <h1>Change Password</h1>
<form action="" method="post" novalidate>
    {% csrf_token %}
    {{form.as_p}}

    <a href="{% url 'logoutpage' %}">Do you wanna Logout?</a><br>

    <input type="submit" name="" value="Change Password"> 
    
</form>

</div>
<br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br>

{% endblock %}

sports_ecom/neona_sports/templates/checkout.html
{% extends 'base.html' %}
{% load static %}
{% load cart_tag %}
{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

<div class="container">
    <div class="py-5 text-center">

      <div class="row">
        <div class="col-md-4 order-md-2 mb-4">
            <h4 class="d-flex justify-content-between align-items-center mb-3">
                <span class="text-muted">Your cart</span>
              
            </h4>
            <ul class="list-group mb-3 sticky-top">
              {% for key,value in request.session.cart.items %}
                <li class="list-group-item d-flex justify-content-between lh-condensed">
                 
                    <div>
                        <h6 class="my-0">{{value.name}}  X  {{value.quantity}}</h6>
                    </div>
                    <span class="text-muted">{{value.price}}</span>
                    
                </li>
                {% endfor %}
               
             
                <li class="list-group-item d-flex justify-content-between">
                    <span>Total</span>
                    <strong>{{ cart_total_amount| add:100 }}</strong>
                </li>
            </ul>

      <h2>Checkout</h2>

    </div>
  </div>

  <div class="container">
    <h4 class="mb-3">Biiling Details</h4>
    <form action="" autocomplete="off" method="POST">
          {% csrf_token %}
      <div class="row">
        <div class="col-sm-6">
          <label for="" class="form-label">First Name</label>
          <input type="text" name="firstname" id="" value="{{user.first_name}}" class="form-control">
        </div>

        <div class="col-sm-6">
          <label for="" class="form-label">Last Name</label>
          <input type="text" name="lastname" id="" class="form-control">
        </div>

        <div class="col-12">
          <label for="" class="form-label">Email</label>
          <div class="input-group">
            <span class="input-group-text">@</span>
            <input type="text" name="email" id="" value="{{user.email}}" class="form-control">
          </div>
        </div>
        
        <div class="col-sm-6">
          <label for="" class="form-label">Address</label>
          <input type="text" name="address" id="" class="form-control">
        </div>

            
        <div class="col-sm-6">
          <label for="" class="form-label">Phone Number</label>
          <input type="text" name="mobile" id="" class="form-control">
        </div>


          <hr class="my-4">

        <input type="submit" id="btn_send" value="Place order">
        </div>
      </div>
    </form>
  </div>
  

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
    crossorigin="anonymous"></script>
{% endblock %}

sports_ecom/neona_sports/templates/login.html
<!DOCTYPE html>
<html>
{% load static %}
<link rel="stylesheet" href="{% static 'css/style.css'%}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

<head>
    <title>Login Page</title>
</head>

<body style="background-image: url('{% static 'images/4.jpg' %}')">

    {% include 'messages.html' %}


    <img src="{% static 'images/logo1.png'%}" width="90px">

    <div class="loginbox">
        <img src="{% static 'images/logo.png'%}" class="avatar">

        <h1>Login</h1>
        <form method="post">
            {% csrf_token %}

            <p>Username</p>
            <input type="text" name="username" placeholder="Enter Username">
            <p>password</p>
            <input type="password" name="pass" placeholder="Enter Password">
            <input type="submit" name="" value="Login">
            <a href="{% url 'password_reset' %}"> Forget your password</a><br>
            <a href="{% url 'signup' %}"> Don't have an Account?</a><br>
            <a href="{% url 'adminlogin' %}"> Login as Admin</a>




        </form>

    </div>




    </div>
    <script src="{% static 'js/grid.js' %}"></script>
    <script>
        setTimeout(function()
        {
            if($('#message').length > 0){
                $('#message').remove();
            }
        }, 2000)
    </script>
</body>

</html>

sports_ecom/neona_sports/templates/messages.html
{% for message in messages %}

  <div class="alert {{ message.tags }} mb-0 alert-dismissible" role="alert" >
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="True">&times;</span>
    </button>
    {{ message }}
  </div>
</div>
{% endfor %}